FROM node:10.17.0

WORKDIR '/app'

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
ADD package.json /app/package.json
RUN npm install

# add app
ADD . /app

EXPOSE 3001
# start app
CMD node server/index.js